language: node_js
cache:
  directories:
    - node_modules
install:
  - npm ci
  - npm i -g codecov
script:
  - npm test
  - codecov
  - npm run build
deploy:
  provider: firebase
  skip_cleanup: true
  token:
    secure: $FIREBASE_TOKEN
  on:
    branch: master